openapi: 3.0.1
info:
    title: API Documentation
    version: 1.0.0
paths:
    /users:
        get:
            summary: Get all users
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
        post:
            summary: Create a user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
    /users/{id}:
        get:
            summary: Get a user by ID
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
        put:
            summary: Update a user
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  schema:
                      type: integer
                - name: user
                  in: requestBody
                  description: User object
                  required: true
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/User'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
        delete:
            summary: Delete a user
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  schema:
                      type: integer
            responses:
                '204':
                    description: No Content
    /posts:
        get:
            summary: Get all posts
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Post'
        post:
            summary: Create a post
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Post'
    /posts/{id}:
        get:
            summary: Get a post by ID
            parameters:
                - name: id
                  in: path
                  description: Post ID
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Post'
        put:
            summary: Update a post
            parameters:
                - name: id
                  in: path
                  description: Post ID
                  required: true
                  schema:
                      type: integer
                - name: post
                  in: requestBody
                  description: Post object
                  required: true
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/Post'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Post'
        delete:
            summary: Delete a post
            parameters:
                - name: id
                  in: path
                  description: Post ID
                  required: true
                  schema:
                      type: integer
            responses:
                '204':
                    description: No Content
    /categories:
        get:
            summary: Get all categories
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Category'
        post:
            summary: Create a category
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Category'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Category'
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                email:
                    type: string
                name:
                    type: string
                posts:
                    type: array
                    items:
                        $ref: '#/components/schemas/Post'
                categories:
                    type: array
                    items:
                        $ref: '#/components/schemas/Category'
                tags:
                    type: array
                    items:
                        $ref: '#/components/schemas/Tag'
                likes:
                    type: array
                    items:
                        $ref: '#/components/schemas/Like'
        Post:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                title:
                    type: string
                content:
                    type: string
                published:
                    type: boolean
                author:
                    $ref: '#/components/schemas/User'
                authorId:
                    type: integer
                    format: int32
                category:
                    $ref: '#/components/schemas/Category'
                categoryId:
                    type: integer
                    format: int32
                tags:
                    type: array
                    items:
                        $ref: '#/components/schemas/Tag'
                likes:
                    type: array
                    items:
                        $ref: '#/components/schemas/Like'
        Category:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                name:
                    type: string
                authorId:
                    type: integer
                    format: int32
                author:
                    $ref: '#/components/schemas/User'
                posts:
                    type: array
                    items:
                        $ref: '#/components/schemas/Post'
        Tag:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                name:
                    type: string
                posts:
                    type: array
                    items:
                        $ref: '#/components/schemas/Post'
                authorId:
                    type: integer
                    format: int32
                author:
                    $ref: '#/components/schemas/User'
        Like:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                postId:
                    type: integer
                    format: int32
                post:
                    $ref: '#/components/schemas/Post'
                author:
                    $ref: '#/components/schemas/User'
                authorId:
                    type: integer
                    format: int32
